version: "3.9"

services:
  backend:
    build:
      context: ./backend
    ports:
      - "4000:4000"
    env_file: .env.e2e
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      backend:
        condition: service_healthy

  db:
    image: postgres:15-alpine
    env_file: .env.e2e
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d ulas -U ulas"]
      retries: 5
    # volumes:
    #   - pgdata_new1:/var/lib/postgresql/data

  e2e:
    build: ./e2e
    volumes:
      - ./e2e/playwright-report:/app/playwright-report
      - ./e2e/test-results:/app/test-results
    command: npx playwright test
    depends_on:
      frontend:
        condition: service_healthy
